AC_DEFUN([AX_SILOFS_NEED_COMPILER],
[
  AC_PROG_CC
  AC_PROG_CC_C_O
  AC_PROG_CPP
  AC_PROG_CXX
  AC_PROG_LN_S
  AC_PROG_RANLIB
])

AC_DEFUN([AX_SILOFS_WANT_COMPILER_OPTS],
[
  AC_C_VOLATILE
  AX_C___ATTRIBUTE__
  AX_COMPILER_VENDOR
  AX_COMPILER_FLAGS
  AX_CFLAGS_WARN_ALL
])
