AC_DEFUN([AX_SILOFS_NEED_COMPILER],
[
  AC_PROG_CC
  AC_PROG_CC_C_O
  AC_PROG_CPP
  AC_PROG_LN_S
  AC_PROG_RANLIB
  AX_PROG_CC_FOR_BUILD
])

AC_DEFUN([AX_SILOFS_WANT_COMPILER_OPTS],
[
  AC_C_BIGENDIAN
  AX_C___ATTRIBUTE__
  AX_COMPILER_VENDOR
  AX_COMPILER_FLAGS
  AX_CFLAGS_WARN_ALL

  AX_CHECK_COMPILE_FLAG([-Werror], [CFLAGS="$CFLAGS -Werror"])
  AX_CHECK_COMPILE_FLAG([-std=gnu23], [CFLAGS="$CFLAGS -std=gnu23"])
])
