---
Checks: >
  -*,
  bugprone-*,
  -bugprone-easily-swappable-parameters,
  -bugprone-reserved-identifier,
  cert-*,
  -cert-dcl37-c,
  -cert-dcl51-cpp,
  -cert-err33-c,
  -cert-err34-c,
  clang-analyzer-*,
  -clang-analyzer-optin.core.EnumCastOutOfRange,
  -clang-analyzer-optin.performance.Padding,
  -clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling,
  -clang-analyzer-valist.Uninitialized,
  misc-*,
  -misc-include-cleaner,
  -misc-no-recursion,
  modernize-*,
  performance-*,
  -performance-no-int-to-ptr,
  portability-*
  readability-*,
  -readability-identifier-length,
  -readability-magic-numbers,
WarningsAsErrors: '*'
FormatStyle: file
CheckOptions:
  - key: readability-identifier-naming.VariableCase
    value: lower_case
  - key: readability-identifier-naming.FunctionCase
    value: lower_case
  - key: readability-identifier-naming.EnumCase
    value: lower_case
UseColor: false
