noinst_HEADERS = $(NULL)
noinst_HEADERS += silofs/flags.h
noinst_HEADERS += silofs/base/atomic.h
noinst_HEADERS += silofs/base/avl.h
noinst_HEADERS += silofs/base/base64.h
noinst_HEADERS += silofs/base/bytebuf.h
noinst_HEADERS += silofs/base/iovec.h
noinst_HEADERS += silofs/base/hamming.h
noinst_HEADERS += silofs/base/hashfn.h
noinst_HEADERS += silofs/base/list.h
noinst_HEADERS += silofs/base/pipe.h
noinst_HEADERS += silofs/base/private.h
noinst_HEADERS += silofs/base/qalloc.h
noinst_HEADERS += silofs/base/socket.h
noinst_HEADERS += silofs/base/thread.h
noinst_HEADERS += silofs/base/times.h
noinst_HEADERS += silofs/base/uconv.h
noinst_HEADERS += silofs/base/utility.h
noinst_HEADERS += silofs/base/uuid.h
noinst_HEADERS += silofs/base/zcmpr.h
noinst_HEADERS += silofs/base.h
noinst_HEADERS += silofs/str/ascii.h
noinst_HEADERS += silofs/str/strbuf.h
noinst_HEADERS += silofs/str/strchr.h
noinst_HEADERS += silofs/str/strspan.h
noinst_HEADERS += silofs/str/strview.h
noinst_HEADERS += silofs/str.h
noinst_HEADERS += silofs/crypt.h
noinst_HEADERS += silofs/addr.h
noinst_HEADERS += silofs/nodes.h
noinst_HEADERS += silofs/pv.h
noinst_HEADERS += silofs/vfs.h
noinst_HEADERS += silofs/fs/dir.h
noinst_HEADERS += silofs/fs/encdec.h
noinst_HEADERS += silofs/fs/file.h
noinst_HEADERS += silofs/fs/flush.h
noinst_HEADERS += silofs/fs/inode.h
noinst_HEADERS += silofs/fs/lcache.h
noinst_HEADERS += silofs/fs/lsmap.h
noinst_HEADERS += silofs/fs/namei.h
noinst_HEADERS += silofs/fs/spmaps.h
noinst_HEADERS += silofs/fs/spxmap.h
noinst_HEADERS += silofs/fs/super.h
noinst_HEADERS += silofs/fs/symlink.h
noinst_HEADERS += silofs/fs/task.h
noinst_HEADERS += silofs/fs/vstage.h
noinst_HEADERS += silofs/fs/xattr.h
noinst_HEADERS += silofs/fs.h
noinst_HEADERS += silofs/ar/archive.h
noinst_HEADERS += silofs/ar/index.h
noinst_HEADERS += silofs/ar.h
noinst_HEADERS += silofs/run.h
noinst_HEADERS += silofs/fuseq.h
noinst_HEADERS += silofs/run/env.h
noinst_HEADERS += silofs/run/mbr.h
noinst_HEADERS += silofs/run/opers.h
noinst_HEADERS += silofs/run/walk.h
