FROM ubuntu:latest AS builder
ARG DISTNAME="silofs-0.0.0"
WORKDIR /scratch
RUN apt-get update -y
RUN apt-get upgrade -y
COPY $DISTNAME.tar.gz .
RUN tar xvfz $DISTNAME.tar.gz
RUN $DISTNAME/pkg/deb/install-deb-deps.sh --base
RUN $DISTNAME/pkg/deb/packagize-deb.sh
RUN cp $DISTNAME/build/pkg/silofs_*.deb /scratch/
RUN rm -rf /scratch/$DISTNAME/*

FROM ubuntu:latest
WORKDIR /tmp
COPY --from=builder /scratch/silofs_*.deb /tmp/
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y -f /tmp/silofs_*.deb
RUN silofs --version
RUN rm -f /tmp/silofs_*.deb
