FROM docker.io/library/ubuntu:noble
WORKDIR /scratch
RUN apt update -y
RUN apt install -y tzdata
ENV TZ="America/New_York"
RUN apt upgrade -y
COPY install-deb-deps.sh .
RUN ./install-deb-deps.sh --all
RUN rm -f /scratch/*

