-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

libsilofsdir = $(libdir)
libsilofs_LTLIBRARIES = libsilofs.la
libsilofs_la_LDFLAGS = $(NULL)
libsilofs_la_LDFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
libsilofs_la_LDFLAGS += -version-info 0
libsilofs_la_CPPFLAGS = $(NULL)
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/include
libsilofs_la_CPPFLAGS += -I$(top_builddir)/include
libsilofs_la_CPPFLAGS += -DSILOFS_USE_PRIVATE=1
libsilofs_la_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
libsilofs_la_LIBADD = $(NULL)
libsilofs_la_LIBADD += @LIBS@
libsilofs_la_LIBADD += $(PTHREAD_LIBS)
libsilofs_la_SOURCES = $(NULL)
libsilofs_la_SOURCES += silofs/flags.h
libsilofs_la_SOURCES += silofs/ondisk.c
libsilofs_la_SOURCES += silofs/version.c
libsilofs_la_SOURCES += silofs/sys/syscall.c
libsilofs_la_SOURCES += silofs/sys/syscallx.c
libsilofs_la_SOURCES += silofs/infra/atomic.h
libsilofs_la_SOURCES += silofs/infra/avl.c
libsilofs_la_SOURCES += silofs/infra/avl.h
libsilofs_la_SOURCES += silofs/infra/base64.c
libsilofs_la_SOURCES += silofs/infra/base64.h
libsilofs_la_SOURCES += silofs/infra/bytebuf.c
libsilofs_la_SOURCES += silofs/infra/bytebuf.h
libsilofs_la_SOURCES += silofs/infra/iovec.c
libsilofs_la_SOURCES += silofs/infra/iovec.h
libsilofs_la_SOURCES += silofs/infra/hashfn.c
libsilofs_la_SOURCES += silofs/infra/hashfn.h
libsilofs_la_SOURCES += silofs/infra/list.c
libsilofs_la_SOURCES += silofs/infra/list.h
libsilofs_la_SOURCES += silofs/infra/logging.c
libsilofs_la_SOURCES += silofs/infra/memalloc.c
libsilofs_la_SOURCES += silofs/infra/panic.c
libsilofs_la_SOURCES += silofs/infra/pipe.c
libsilofs_la_SOURCES += silofs/infra/pipe.h
libsilofs_la_SOURCES += silofs/infra/private.h
libsilofs_la_SOURCES += silofs/infra/qalloc.c
libsilofs_la_SOURCES += silofs/infra/qalloc.h
libsilofs_la_SOURCES += silofs/infra/snprintf.c
libsilofs_la_SOURCES += silofs/infra/snprintf.h
libsilofs_la_SOURCES += silofs/infra/socket.c
libsilofs_la_SOURCES += silofs/infra/socket.h
libsilofs_la_SOURCES += silofs/infra/thread.c
libsilofs_la_SOURCES += silofs/infra/thread.h
libsilofs_la_SOURCES += silofs/infra/times.c
libsilofs_la_SOURCES += silofs/infra/times.h
libsilofs_la_SOURCES += silofs/infra/uconv.c
libsilofs_la_SOURCES += silofs/infra/uconv.h
libsilofs_la_SOURCES += silofs/infra/utility.h
libsilofs_la_SOURCES += silofs/infra/uuid.c
libsilofs_la_SOURCES += silofs/infra/uuid.h
libsilofs_la_SOURCES += silofs/infra/zcmpr.c
libsilofs_la_SOURCES += silofs/infra/zcmpr.h
libsilofs_la_SOURCES += silofs/infra.h
libsilofs_la_SOURCES += silofs/str/ascii.c
libsilofs_la_SOURCES += silofs/str/ascii.h
libsilofs_la_SOURCES += silofs/str/strbuf.c
libsilofs_la_SOURCES += silofs/str/strbuf.h
libsilofs_la_SOURCES += silofs/str/strchr.c
libsilofs_la_SOURCES += silofs/str/strchr.h
libsilofs_la_SOURCES += silofs/str/strspan.c
libsilofs_la_SOURCES += silofs/str/strspan.h
libsilofs_la_SOURCES += silofs/str/strview.c
libsilofs_la_SOURCES += silofs/str/strview.h
libsilofs_la_SOURCES += silofs/str.h
libsilofs_la_SOURCES += silofs/crypto/cipher.c
libsilofs_la_SOURCES += silofs/crypto/cipher.h
libsilofs_la_SOURCES += silofs/crypto/gcry.c
libsilofs_la_SOURCES += silofs/crypto/gcry.h
libsilofs_la_SOURCES += silofs/crypto/hmac.c
libsilofs_la_SOURCES += silofs/crypto/hmac.h
libsilofs_la_SOURCES += silofs/crypto/ivkey.c
libsilofs_la_SOURCES += silofs/crypto/ivkey.h
libsilofs_la_SOURCES += silofs/crypto/kdf.c
libsilofs_la_SOURCES += silofs/crypto/kdf.h
libsilofs_la_SOURCES += silofs/crypto/mdigest.c
libsilofs_la_SOURCES += silofs/crypto/mdigest.h
libsilofs_la_SOURCES += silofs/crypto/passwd.c
libsilofs_la_SOURCES += silofs/crypto/passwd.h
libsilofs_la_SOURCES += silofs/crypto/prand.c
libsilofs_la_SOURCES += silofs/crypto/prand.h
libsilofs_la_SOURCES += silofs/crypto.h
libsilofs_la_SOURCES += silofs/addr/blobid.c
libsilofs_la_SOURCES += silofs/addr/blobid.h
libsilofs_la_SOURCES += silofs/addr/fsref.c
libsilofs_la_SOURCES += silofs/addr/fsref.h
libsilofs_la_SOURCES += silofs/addr/genid.c
libsilofs_la_SOURCES += silofs/addr/genid.h
libsilofs_la_SOURCES += silofs/addr/hash.c
libsilofs_la_SOURCES += silofs/addr/hash.h
libsilofs_la_SOURCES += silofs/addr/htox.c
libsilofs_la_SOURCES += silofs/addr/htox.h
libsilofs_la_SOURCES += silofs/addr/laddr.c
libsilofs_la_SOURCES += silofs/addr/laddr.h
libsilofs_la_SOURCES += silofs/addr/mbref.c
libsilofs_la_SOURCES += silofs/addr/mbref.h
libsilofs_la_SOURCES += silofs/addr/nmeta.c
libsilofs_la_SOURCES += silofs/addr/nmeta.h
libsilofs_la_SOURCES += silofs/addr/pnptr.c
libsilofs_la_SOURCES += silofs/addr/pnptr.h
libsilofs_la_SOURCES += silofs/addr/offlba.c
libsilofs_la_SOURCES += silofs/addr/offlba.h
libsilofs_la_SOURCES += silofs/addr/paddr.c
libsilofs_la_SOURCES += silofs/addr/paddr.h
libsilofs_la_SOURCES += silofs/addr/spdesc.c
libsilofs_la_SOURCES += silofs/addr/spdesc.h
libsilofs_la_SOURCES += silofs/addr/stype.c
libsilofs_la_SOURCES += silofs/addr/stype.h
libsilofs_la_SOURCES += silofs/addr/layerid.c
libsilofs_la_SOURCES += silofs/addr/layerid.h
libsilofs_la_SOURCES += silofs/addr/uaddr.c
libsilofs_la_SOURCES += silofs/addr/uaddr.h
libsilofs_la_SOURCES += silofs/addr/vaddr.c
libsilofs_la_SOURCES += silofs/addr/vaddr.h
libsilofs_la_SOURCES += silofs/addr.h
libsilofs_la_SOURCES += silofs/nodes/dirtyq.c
libsilofs_la_SOURCES += silofs/nodes/dirtyq.h
libsilofs_la_SOURCES += silofs/nodes/hmapq.c
libsilofs_la_SOURCES += silofs/nodes/hmapq.h
libsilofs_la_SOURCES += silofs/nodes/lnodes.c
libsilofs_la_SOURCES += silofs/nodes/lnodes.h
libsilofs_la_SOURCES += silofs/nodes/pcache.c
libsilofs_la_SOURCES += silofs/nodes/pcache.h
libsilofs_la_SOURCES += silofs/nodes/pnodes.c
libsilofs_la_SOURCES += silofs/nodes/pnodes.h
libsilofs_la_SOURCES += silofs/nodes/vcache.c
libsilofs_la_SOURCES += silofs/nodes/vcache.h
libsilofs_la_SOURCES += silofs/nodes/view.c
libsilofs_la_SOURCES += silofs/nodes/view.h
libsilofs_la_SOURCES += silofs/nodes.h
libsilofs_la_SOURCES += silofs/pv/bldesc.c
libsilofs_la_SOURCES += silofs/pv/bldesc.h
libsilofs_la_SOURCES += silofs/pv/dstor.c
libsilofs_la_SOURCES += silofs/pv/dstor.h
libsilofs_la_SOURCES += silofs/pv/pexec.h
libsilofs_la_SOURCES += silofs/pv/btnode.c
libsilofs_la_SOURCES += silofs/pv/btnode.h
libsilofs_la_SOURCES += silofs/pv/btree.c
libsilofs_la_SOURCES += silofs/pv/btree.h
libsilofs_la_SOURCES += silofs/pv/carve.c
libsilofs_la_SOURCES += silofs/pv/carve.h
libsilofs_la_SOURCES += silofs/pv/repo.c
libsilofs_la_SOURCES += silofs/pv/repo.h
libsilofs_la_SOURCES += silofs/pv/space.c
libsilofs_la_SOURCES += silofs/pv/space.h
libsilofs_la_SOURCES += silofs/pv/stage.c
libsilofs_la_SOURCES += silofs/pv/stage.h
libsilofs_la_SOURCES += silofs/pv/uber.c
libsilofs_la_SOURCES += silofs/pv/uber.h
libsilofs_la_SOURCES += silofs/pv.h
libsilofs_la_SOURCES += silofs/fs/claim.c
libsilofs_la_SOURCES += silofs/fs/dir.c
libsilofs_la_SOURCES += silofs/fs/dir.h
libsilofs_la_SOURCES += silofs/fs/encdec.c
libsilofs_la_SOURCES += silofs/fs/encdec.h
libsilofs_la_SOURCES += silofs/fs/file.c
libsilofs_la_SOURCES += silofs/fs/file.h
libsilofs_la_SOURCES += silofs/fs/flush.c
libsilofs_la_SOURCES += silofs/fs/flush.h
libsilofs_la_SOURCES += silofs/fs/idsmap.c
libsilofs_la_SOURCES += silofs/fs/idsmap.h
libsilofs_la_SOURCES += silofs/fs/inode.c
libsilofs_la_SOURCES += silofs/fs/inode.h
libsilofs_la_SOURCES += silofs/fs/lcache.c
libsilofs_la_SOURCES += silofs/fs/lcache.h
libsilofs_la_SOURCES += silofs/fs/lsmap.c
libsilofs_la_SOURCES += silofs/fs/lsmap.h
libsilofs_la_SOURCES += silofs/fs/lspace.c
libsilofs_la_SOURCES += silofs/fs/lspace.h
libsilofs_la_SOURCES += silofs/fs/namei.c
libsilofs_la_SOURCES += silofs/fs/namei.h
libsilofs_la_SOURCES += silofs/fs/sbstat.c
libsilofs_la_SOURCES += silofs/fs/spmaps.c
libsilofs_la_SOURCES += silofs/fs/spmaps.h
libsilofs_la_SOURCES += silofs/fs/spxmap.c
libsilofs_la_SOURCES += silofs/fs/spxmap.h
libsilofs_la_SOURCES += silofs/fs/super.c
libsilofs_la_SOURCES += silofs/fs/super.h
libsilofs_la_SOURCES += silofs/fs/symlink.c
libsilofs_la_SOURCES += silofs/fs/symlink.h
libsilofs_la_SOURCES += silofs/fs/uidgid.c
libsilofs_la_SOURCES += silofs/fs/uidgid.h
libsilofs_la_SOURCES += silofs/fs/ustage.c
libsilofs_la_SOURCES += silofs/fs/vfs.h
libsilofs_la_SOURCES += silofs/fs/vstage.c
libsilofs_la_SOURCES += silofs/fs/vstage.h
libsilofs_la_SOURCES += silofs/fs/xattr.c
libsilofs_la_SOURCES += silofs/fs/xattr.h
libsilofs_la_SOURCES += silofs/fs.h
libsilofs_la_SOURCES += silofs/ar/archive.c
libsilofs_la_SOURCES += silofs/ar/archive.h
libsilofs_la_SOURCES += silofs/ar/hamming.c
libsilofs_la_SOURCES += silofs/ar/hamming.h
libsilofs_la_SOURCES += silofs/ar/index.c
libsilofs_la_SOURCES += silofs/ar/index.h
libsilofs_la_SOURCES += silofs/ar.h
libsilofs_la_SOURCES += silofs/mnt/mntconf.c
libsilofs_la_SOURCES += silofs/mnt/mntsvc.c
libsilofs_la_SOURCES += silofs/run/appexec.c
libsilofs_la_SOURCES += silofs/run/delfs.c
libsilofs_la_SOURCES += silofs/run/env.c
libsilofs_la_SOURCES += silofs/run/env.h
libsilofs_la_SOURCES += silofs/run/envinst.c
libsilofs_la_SOURCES += silofs/run/ignite.c
libsilofs_la_SOURCES += silofs/run/mbr.c
libsilofs_la_SOURCES += silofs/run/mbr.h
libsilofs_la_SOURCES += silofs/run/opers.c
libsilofs_la_SOURCES += silofs/run/opers.h
libsilofs_la_SOURCES += silofs/run/task.c
libsilofs_la_SOURCES += silofs/run/task.h
libsilofs_la_SOURCES += silofs/run/vfswrap.c
libsilofs_la_SOURCES += silofs/run/walk.c
libsilofs_la_SOURCES += silofs/run/walk.h
libsilofs_la_SOURCES += silofs/run.h
libsilofs_la_SOURCES += silofs/fuse/fuse_abi.h
libsilofs_la_SOURCES += silofs/fuse/fuseq.c
libsilofs_la_SOURCES += silofs/fuse/fuseq.h
libsilofs_la_SOURCES += silofs/fuse.h
