-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

noinst_HEADERS = configs.h

libsilofsdir = $(libdir)
libsilofs_LTLIBRARIES = libsilofs.la
libsilofs_la_LDFLAGS = $(NULL)
libsilofs_la_LDFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
libsilofs_la_LDFLAGS += -version-info 0
libsilofs_la_CPPFLAGS = $(NULL)
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/include
libsilofs_la_CPPFLAGS += -DSILOFS_USE_PRIVATE=1
libsilofs_la_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
libsilofs_la_LIBADD = $(NULL)
libsilofs_la_LIBADD += @LIBS@
libsilofs_la_LIBADD += $(PTHREAD_LIBS)
libsilofs_la_SOURCES = $(NULL)
libsilofs_la_SOURCES += sys/syscall.c
libsilofs_la_SOURCES += sys/syscallx.c
libsilofs_la_SOURCES += infra/atomic.h
libsilofs_la_SOURCES += infra/avl.c
libsilofs_la_SOURCES += infra/avl.h
libsilofs_la_SOURCES += infra/base64.c
libsilofs_la_SOURCES += infra/base64.h
libsilofs_la_SOURCES += infra/bytebuf.c
libsilofs_la_SOURCES += infra/bytebuf.h
libsilofs_la_SOURCES += infra/iovec.c
libsilofs_la_SOURCES += infra/iovec.h
libsilofs_la_SOURCES += infra/hash.c
libsilofs_la_SOURCES += infra/hash.h
libsilofs_la_SOURCES += infra/list.c
libsilofs_la_SOURCES += infra/list.h
libsilofs_la_SOURCES += infra/logging.c
libsilofs_la_SOURCES += infra/memalloc.c
libsilofs_la_SOURCES += infra/panic.c
libsilofs_la_SOURCES += infra/pipe.c
libsilofs_la_SOURCES += infra/pipe.h
libsilofs_la_SOURCES += infra/private.h
libsilofs_la_SOURCES += infra/qalloc.c
libsilofs_la_SOURCES += infra/qalloc.h
libsilofs_la_SOURCES += infra/random.c
libsilofs_la_SOURCES += infra/socket.c
libsilofs_la_SOURCES += infra/socket.h
libsilofs_la_SOURCES += infra/thread.c
libsilofs_la_SOURCES += infra/times.c
libsilofs_la_SOURCES += infra/times.h
libsilofs_la_SOURCES += infra/uconv.c
libsilofs_la_SOURCES += infra/uconv.h
libsilofs_la_SOURCES += infra/utility.h
libsilofs_la_SOURCES += infra/zcmpr.c
libsilofs_la_SOURCES += infra/zcmpr.h
libsilofs_la_SOURCES += infra.h
libsilofs_la_SOURCES += str/ascii.c
libsilofs_la_SOURCES += str/ascii.h
libsilofs_la_SOURCES += str/strbuf.c
libsilofs_la_SOURCES += str/strbuf.h
libsilofs_la_SOURCES += str/strchr.c
libsilofs_la_SOURCES += str/strchr.h
libsilofs_la_SOURCES += str/strspan.c
libsilofs_la_SOURCES += str/strspan.h
libsilofs_la_SOURCES += str/strview.c
libsilofs_la_SOURCES += str/strview.h
libsilofs_la_SOURCES += str.h
libsilofs_la_SOURCES += crypt/cipher.c
libsilofs_la_SOURCES += crypt/cipher.h
libsilofs_la_SOURCES += crypt/gcry.c
libsilofs_la_SOURCES += crypt/gcry.h
libsilofs_la_SOURCES += crypt/ivkey.c
libsilofs_la_SOURCES += crypt/ivkey.h
libsilofs_la_SOURCES += crypt/mdigest.c
libsilofs_la_SOURCES += crypt/mdigest.h
libsilofs_la_SOURCES += crypt/passwd.c
libsilofs_la_SOURCES += crypt/passwd.h
libsilofs_la_SOURCES += crypt.h
libsilofs_la_SOURCES += addr/blobid.c
libsilofs_la_SOURCES += addr/blobid.h
libsilofs_la_SOURCES += addr/htox.c
libsilofs_la_SOURCES += addr/htox.h
libsilofs_la_SOURCES += addr/laddr.c
libsilofs_la_SOURCES += addr/laddr.h
libsilofs_la_SOURCES += addr/meta.c
libsilofs_la_SOURCES += addr/meta.h
libsilofs_la_SOURCES += addr/mtype.c
libsilofs_la_SOURCES += addr/mtype.h
libsilofs_la_SOURCES += addr/offlba.c
libsilofs_la_SOURCES += addr/offlba.h
libsilofs_la_SOURCES += addr/paddr.c
libsilofs_la_SOURCES += addr/paddr.h
libsilofs_la_SOURCES += addr/svolid.c
libsilofs_la_SOURCES += addr/svolid.h
libsilofs_la_SOURCES += addr/uaddr.c
libsilofs_la_SOURCES += addr/uaddr.h
libsilofs_la_SOURCES += addr/uuid.c
libsilofs_la_SOURCES += addr/uuid.h
libsilofs_la_SOURCES += addr/vaddr.c
libsilofs_la_SOURCES += addr/vaddr.h
libsilofs_la_SOURCES += addr.h
libsilofs_la_SOURCES += nodes/dirtyq.c
libsilofs_la_SOURCES += nodes/dirtyq.h
libsilofs_la_SOURCES += nodes/hmapq.c
libsilofs_la_SOURCES += nodes/hmapq.h
libsilofs_la_SOURCES += nodes/pcache.c
libsilofs_la_SOURCES += nodes/pcache.h
libsilofs_la_SOURCES += nodes/pnodes.c
libsilofs_la_SOURCES += nodes/pnodes.h
libsilofs_la_SOURCES += nodes/view.c
libsilofs_la_SOURCES += nodes/view.h
libsilofs_la_SOURCES += nodes.h
libsilofs_la_SOURCES += bs/bldesc.c
libsilofs_la_SOURCES += bs/bldesc.h
libsilofs_la_SOURCES += bs/btnode.c
libsilofs_la_SOURCES += bs/btnode.h
libsilofs_la_SOURCES += bs/btree.c
libsilofs_la_SOURCES += bs/btree.h
libsilofs_la_SOURCES += bs/locos.c
libsilofs_la_SOURCES += bs/locos.h
libsilofs_la_SOURCES += bs/repo.c
libsilofs_la_SOURCES += bs/repo.h
libsilofs_la_SOURCES += bs/store.c
libsilofs_la_SOURCES += bs/store.h
libsilofs_la_SOURCES += bs/uber.c
libsilofs_la_SOURCES += bs/uber.h
libsilofs_la_SOURCES += bs.h
libsilofs_la_SOURCES += fs/claim.c
libsilofs_la_SOURCES += fs/dir.c
libsilofs_la_SOURCES += fs/dir.h
libsilofs_la_SOURCES += fs/encdec.c
libsilofs_la_SOURCES += fs/encdec.h
libsilofs_la_SOURCES += fs/exec.c
libsilofs_la_SOURCES += fs/exec.h
libsilofs_la_SOURCES += fs/file.c
libsilofs_la_SOURCES += fs/file.h
libsilofs_la_SOURCES += fs/flush.c
libsilofs_la_SOURCES += fs/idsmap.c
libsilofs_la_SOURCES += fs/idsmap.h
libsilofs_la_SOURCES += fs/inode.c
libsilofs_la_SOURCES += fs/inode.h
libsilofs_la_SOURCES += fs/lcache.c
libsilofs_la_SOURCES += fs/lcache.h
libsilofs_la_SOURCES += fs/lnodes.c
libsilofs_la_SOURCES += fs/lnodes.h
libsilofs_la_SOURCES += fs/lsmap.c
libsilofs_la_SOURCES += fs/lsmap.h
libsilofs_la_SOURCES += fs/namei.c
libsilofs_la_SOURCES += fs/namei.h
libsilofs_la_SOURCES += fs/sbstat.c
libsilofs_la_SOURCES += fs/spmaps.c
libsilofs_la_SOURCES += fs/spmaps.h
libsilofs_la_SOURCES += fs/spxmap.c
libsilofs_la_SOURCES += fs/spxmap.h
libsilofs_la_SOURCES += fs/stage.h
libsilofs_la_SOURCES += fs/super.c
libsilofs_la_SOURCES += fs/super.h
libsilofs_la_SOURCES += fs/symlink.c
libsilofs_la_SOURCES += fs/symlink.h
libsilofs_la_SOURCES += fs/uidgid.h
libsilofs_la_SOURCES += fs/ustage.c
libsilofs_la_SOURCES += fs/vstage.c
libsilofs_la_SOURCES += fs/xattr.c
libsilofs_la_SOURCES += fs/xattr.h
libsilofs_la_SOURCES += fs.h
libsilofs_la_SOURCES += ar/archive.c
libsilofs_la_SOURCES += ar/arre.h
libsilofs_la_SOURCES += ar/hamming.c
libsilofs_la_SOURCES += ar/hamming.h
libsilofs_la_SOURCES += ar/index.c
libsilofs_la_SOURCES += ar/index.h
libsilofs_la_SOURCES += ar/restore.c
libsilofs_la_SOURCES += ar.h
libsilofs_la_SOURCES += affirm.c
libsilofs_la_SOURCES += appexec.c
libsilofs_la_SOURCES += delfs.c
libsilofs_la_SOURCES += env.c
libsilofs_la_SOURCES += env.h
libsilofs_la_SOURCES += envboot.c
libsilofs_la_SOURCES += envinst.c
libsilofs_la_SOURCES += flags.h
libsilofs_la_SOURCES += fuseq.c
libsilofs_la_SOURCES += fuseq.h
libsilofs_la_SOURCES += knownfs.h
libsilofs_la_SOURCES += mbr.c
libsilofs_la_SOURCES += mbr.h
libsilofs_la_SOURCES += mntsvc.c
libsilofs_la_SOURCES += opexec.c
libsilofs_la_SOURCES += opexec.h
libsilofs_la_SOURCES += opcall.c
libsilofs_la_SOURCES += opcall.h
libsilofs_la_SOURCES += parseconf.c
libsilofs_la_SOURCES += version.c
libsilofs_la_SOURCES += walk.c
libsilofs_la_SOURCES += walk.h
