-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

bin_PROGRAMS = silofs-ftests
silofs_ftests_CPPFLAGS = $(NULL)
silofs_ftests_CPPFLAGS += -I$(top_srcdir)/include
silofs_ftests_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
silofs_ftests_LDFLAGS = $(NULL)
silofs_ftests_LDFLAGS += -L$(top_builddir)/lib
silofs_ftests_LDFLAGS += -static
silofs_ftests_LDADD = @LIBS@
silofs_ftests_LDADD += $(top_builddir)/lib/libsilofs.la
silofs_ftests_LDADD += $(PTHREAD_LIBS)
silofs_ftests_LDADD += $(LIBGCRYPT_LIBS)
silofs_ftests_SOURCES = $(NULL)
silofs_ftests_SOURCES += ftests.h
silofs_ftests_SOURCES += ftests_expect.c
silofs_ftests_SOURCES += ftests_expect.h
silofs_ftests_SOURCES += ftests_inline.h
silofs_ftests_SOURCES += ftests_main.c
silofs_ftests_SOURCES += ftests_run.c
silofs_ftests_SOURCES += ftests_syscall.c
silofs_ftests_SOURCES += ftests_syscall.h
silofs_ftests_SOURCES += ftests_utility.c
silofs_ftests_SOURCES += test_access.c
silofs_ftests_SOURCES += test_boundaries.c
silofs_ftests_SOURCES += test_chmod_chown.c
silofs_ftests_SOURCES += test_copy_file_range.c
silofs_ftests_SOURCES += test_create.c
silofs_ftests_SOURCES += test_fallocate.c
silofs_ftests_SOURCES += test_fiemap.c
silofs_ftests_SOURCES += test_fifo.c
silofs_ftests_SOURCES += test_fsync.c
silofs_ftests_SOURCES += test_link.c
silofs_ftests_SOURCES += test_lseek.c
silofs_ftests_SOURCES += test_mkdir_rmdir.c
silofs_ftests_SOURCES += test_mmap.c
silofs_ftests_SOURCES += test_mmap_mt.c
silofs_ftests_SOURCES += test_mt_rw_basic.c
silofs_ftests_SOURCES += test_namespace.c
silofs_ftests_SOURCES += test_opath.c
silofs_ftests_SOURCES += test_open.c
silofs_ftests_SOURCES += test_readdir.c
silofs_ftests_SOURCES += test_rename.c
silofs_ftests_SOURCES += test_rw_basic.c
silofs_ftests_SOURCES += test_rw_large.c
silofs_ftests_SOURCES += test_rw_osync.c
silofs_ftests_SOURCES += test_rw_random.c
silofs_ftests_SOURCES += test_rw_sequential.c
silofs_ftests_SOURCES += test_rw_sparse.c
silofs_ftests_SOURCES += test_stat.c
silofs_ftests_SOURCES += test_stat_io.c
silofs_ftests_SOURCES += test_statvfs.c
silofs_ftests_SOURCES += test_statx.c
silofs_ftests_SOURCES += test_symlink.c
silofs_ftests_SOURCES += test_tmpfile.c
silofs_ftests_SOURCES += test_truncate.c
silofs_ftests_SOURCES += test_truncate_file.c
silofs_ftests_SOURCES += test_unlink.c
silofs_ftests_SOURCES += test_unlinked_file.c
silofs_ftests_SOURCES += test_utimes.c
silofs_ftests_SOURCES += test_write.c
silofs_ftests_SOURCES += test_xattr.c
