-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

bin_PROGRAMS = silofs-ftests
silofs_ftests_CPPFLAGS = $(NULL)
silofs_ftests_CPPFLAGS += -I$(top_builddir)/include
silofs_ftests_CPPFLAGS += -I$(top_srcdir)/include
silofs_ftests_CPPFLAGS += -I$(top_srcdir)/lib
silofs_ftests_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
silofs_ftests_CPPFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
silofs_ftests_LDFLAGS = $(NULL)
silofs_ftests_LDFLAGS += -L$(top_builddir)/lib/silofs
silofs_ftests_LDFLAGS += -static
silofs_ftests_LDADD = $(NULL)
silofs_ftests_LDADD += $(LIBS)
silofs_ftests_LDADD += $(top_builddir)/lib/silofs/libsilofs.la
silofs_ftests_LDADD += $(PTHREAD_LIBS)
silofs_ftests_LDADD += $(LIBGCRYPT_LIBS)
silofs_ftests_SOURCES = $(NULL)
silofs_ftests_SOURCES += ftests.h
silofs_ftests_SOURCES += ftests_expect.c
silofs_ftests_SOURCES += ftests_expect.h
silofs_ftests_SOURCES += ftests_inline.h
silofs_ftests_SOURCES += ftests_main.c
silofs_ftests_SOURCES += ftests_run.c
silofs_ftests_SOURCES += ftests_syscall.c
silofs_ftests_SOURCES += ftests_syscall.h
silofs_ftests_SOURCES += ftests_utility.c
silofs_ftests_SOURCES += ft_access.c
silofs_ftests_SOURCES += ft_chmod_chown.c
silofs_ftests_SOURCES += ft_copy_file_range.c
silofs_ftests_SOURCES += ft_create.c
silofs_ftests_SOURCES += ft_fallocate.c
silofs_ftests_SOURCES += ft_fiemap.c
silofs_ftests_SOURCES += ft_fifo.c
silofs_ftests_SOURCES += ft_fsync.c
silofs_ftests_SOURCES += ft_link.c
silofs_ftests_SOURCES += ft_lseek.c
silofs_ftests_SOURCES += ft_mkdir_rmdir.c
silofs_ftests_SOURCES += ft_mmap.c
silofs_ftests_SOURCES += ft_mmap_mt.c
silofs_ftests_SOURCES += ft_mt_copy_file_range.c
silofs_ftests_SOURCES += ft_mt_rw_basic.c
silofs_ftests_SOURCES += ft_namespace.c
silofs_ftests_SOURCES += ft_opath.c
silofs_ftests_SOURCES += ft_open.c
silofs_ftests_SOURCES += ft_readdir.c
silofs_ftests_SOURCES += ft_rename.c
silofs_ftests_SOURCES += ft_rw_basic.c
silofs_ftests_SOURCES += ft_rw_boundaries.c
silofs_ftests_SOURCES += ft_rw_large.c
silofs_ftests_SOURCES += ft_rw_osync.c
silofs_ftests_SOURCES += ft_rw_random.c
silofs_ftests_SOURCES += ft_rw_sequential.c
silofs_ftests_SOURCES += ft_rw_sparse.c
silofs_ftests_SOURCES += ft_stat.c
silofs_ftests_SOURCES += ft_stat_io.c
silofs_ftests_SOURCES += ft_statvfs.c
silofs_ftests_SOURCES += ft_statx.c
silofs_ftests_SOURCES += ft_symlink.c
silofs_ftests_SOURCES += ft_tmpfile.c
silofs_ftests_SOURCES += ft_truncate.c
silofs_ftests_SOURCES += ft_truncate_file.c
silofs_ftests_SOURCES += ft_unlink.c
silofs_ftests_SOURCES += ft_unlinked_file.c
silofs_ftests_SOURCES += ft_utimes.c
silofs_ftests_SOURCES += ft_write.c
silofs_ftests_SOURCES += ft_xattr.c
