-include $(top_builddir)/sedsub.mk
SUBDIRS = completions sbinutils

AM_CFLAGS = $(WARN_CFLAGS)

bin_PROGRAMS = silofs
silofs_CPPFLAGS = $(NULL)
silofs_CPPFLAGS += -I$(top_srcdir)/include
silofs_CPPFLAGS += -I$(top_builddir)/include
silofs_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
silofs_LDFLAGS = $(NULL)
silofs_LDFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
silofs_LDFLAGS += -L$(builddir)
silofs_LDFLAGS += -L$(top_builddir)/lib
silofs_LDFLAGS += -static
silofs_LDADD = @LIBS@
silofs_LDADD += $(top_builddir)/lib/libsilofs.la
silofs_LDADD += $(PTHREAD_LIBS)
silofs_LDADD += $(LIBGCRYPT_LIBS)
silofs_SOURCES = $(NULL)
silofs_SOURCES += cmd.h
silofs_SOURCES += cmd_archive.c
silofs_SOURCES += cmd_clone.c
silofs_SOURCES += cmd_exec.c
silofs_SOURCES += cmd_fsck.c
silofs_SOURCES += cmd_fsids.c
silofs_SOURCES += cmd_fsref.c
silofs_SOURCES += cmd_getpass.c
silofs_SOURCES += cmd_init.c
silofs_SOURCES += cmd_jconf.c
silofs_SOURCES += cmd_jconf.h
silofs_SOURCES += cmd_locks.c
silofs_SOURCES += cmd_lsmnt.c
silofs_SOURCES += cmd_main.c
silofs_SOURCES += cmd_mkfs.c
silofs_SOURCES += cmd_mount.c
silofs_SOURCES += cmd_optargs.c
silofs_SOURCES += cmd_prune.c
silofs_SOURCES += cmd_restore.c
silofs_SOURCES += cmd_restrict.c
silofs_SOURCES += cmd_rmfs.c
silofs_SOURCES += cmd_show.c
silofs_SOURCES += cmd_signals.c
silofs_SOURCES += cmd_sync.c
silofs_SOURCES += cmd_tune.c
silofs_SOURCES += cmd_umount.c
silofs_SOURCES += cmd_utils.c
silofs_SOURCES += cmd_view.c
