-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

libsilofsdir = $(libdir)
libsilofs_LTLIBRARIES = libsilofs.la
libsilofs_la_CPPFLAGS = $(NULL)
libsilofs_la_CPPFLAGS += -I$(top_builddir)/include
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/include
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/lib
libsilofs_la_CPPFLAGS += -DSILOFS_USE_PRIVATE=1
libsilofs_la_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
libsilofs_la_CPPFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
libsilofs_la_LDFLAGS = $(NULL)
libsilofs_la_LDFLAGS += -version-info 0
libsilofs_la_LIBADD = $(NULL)
libsilofs_la_LIBADD += $(LIBS)
libsilofs_la_LIBADD += $(PTHREAD_LIBS)
libsilofs_la_SOURCES = $(NULL)
libsilofs_la_SOURCES += ondisk.c
libsilofs_la_SOURCES += version.c
libsilofs_la_SOURCES += sys/syscall.c
libsilofs_la_SOURCES += sys/syscallx.c
libsilofs_la_SOURCES += base/avl.c
libsilofs_la_SOURCES += base/base64.c
libsilofs_la_SOURCES += base/bytebuf.c
libsilofs_la_SOURCES += base/iovec.c
libsilofs_la_SOURCES += base/hamming.c
libsilofs_la_SOURCES += base/hashfn.c
libsilofs_la_SOURCES += base/list.c
libsilofs_la_SOURCES += base/logging.c
libsilofs_la_SOURCES += base/memalloc.c
libsilofs_la_SOURCES += base/panic.c
libsilofs_la_SOURCES += base/pipe.c
libsilofs_la_SOURCES += base/qalloc.c
libsilofs_la_SOURCES += base/snprintf.c
libsilofs_la_SOURCES += base/socket.c
libsilofs_la_SOURCES += base/thread.c
libsilofs_la_SOURCES += base/times.c
libsilofs_la_SOURCES += base/uconv.c
libsilofs_la_SOURCES += base/uuid.c
libsilofs_la_SOURCES += base/zcmpr.c
libsilofs_la_SOURCES += str/ascii.c
libsilofs_la_SOURCES += str/strbuf.c
libsilofs_la_SOURCES += str/strchr.c
libsilofs_la_SOURCES += str/strspan.c
libsilofs_la_SOURCES += str/strview.c
libsilofs_la_SOURCES += crypt/cipher.c
libsilofs_la_SOURCES += crypt/gcry.c
libsilofs_la_SOURCES += crypt/hmac.c
libsilofs_la_SOURCES += crypt/ivkey.c
libsilofs_la_SOURCES += crypt/kdf.c
libsilofs_la_SOURCES += crypt/mdigest.c
libsilofs_la_SOURCES += crypt/passwd.c
libsilofs_la_SOURCES += crypt/prand.c
libsilofs_la_SOURCES += addr/blobid.c
libsilofs_la_SOURCES += addr/fsref.c
libsilofs_la_SOURCES += addr/genid.c
libsilofs_la_SOURCES += addr/hash.c
libsilofs_la_SOURCES += addr/htox.c
libsilofs_la_SOURCES += addr/laddr.c
libsilofs_la_SOURCES += addr/mbref.c
libsilofs_la_SOURCES += addr/namestr.c
libsilofs_la_SOURCES += addr/nmeta.c
libsilofs_la_SOURCES += addr/pnptr.c
libsilofs_la_SOURCES += addr/offlba.c
libsilofs_la_SOURCES += addr/paddr.c
libsilofs_la_SOURCES += addr/spdesc.c
libsilofs_la_SOURCES += addr/stype.c
libsilofs_la_SOURCES += addr/layerid.c
libsilofs_la_SOURCES += addr/uaddr.c
libsilofs_la_SOURCES += addr/uidgid.c
libsilofs_la_SOURCES += addr/vaddr.c
libsilofs_la_SOURCES += nodes/dirtyq.c
libsilofs_la_SOURCES += nodes/freesq.c
libsilofs_la_SOURCES += nodes/hmapq.c
libsilofs_la_SOURCES += nodes/nodeview.c
libsilofs_la_SOURCES += nodes/pcache.c
libsilofs_la_SOURCES += nodes/pnodes.c
libsilofs_la_SOURCES += nodes/vcache.c
libsilofs_la_SOURCES += nodes/vnodes.c
libsilofs_la_SOURCES += pv/bldesc.c
libsilofs_la_SOURCES += pv/btnode.c
libsilofs_la_SOURCES += pv/btree.c
libsilofs_la_SOURCES += pv/carve.c
libsilofs_la_SOURCES += pv/encdec.c
libsilofs_la_SOURCES += pv/dstor.c
libsilofs_la_SOURCES += pv/repo.c
libsilofs_la_SOURCES += pv/spnode.c
libsilofs_la_SOURCES += pv/stage.c
libsilofs_la_SOURCES += pv/trans.c
libsilofs_la_SOURCES += pv/uber.c
libsilofs_la_SOURCES += pv/vspace.c
libsilofs_la_SOURCES += pv/vspmap.c
libsilofs_la_SOURCES += fs/dir.c
libsilofs_la_SOURCES += fs/encdec1.c
libsilofs_la_SOURCES += fs/file.c
libsilofs_la_SOURCES += fs/flush.c
libsilofs_la_SOURCES += fs/format.c
libsilofs_la_SOURCES += fs/idsmap.c
libsilofs_la_SOURCES += fs/inode.c
libsilofs_la_SOURCES += fs/inops.c
libsilofs_la_SOURCES += fs/lcache.c
libsilofs_la_SOURCES += fs/lsmap.c
libsilofs_la_SOURCES += fs/pglue.c
libsilofs_la_SOURCES += fs/namei.c
libsilofs_la_SOURCES += fs/sbstat.c
libsilofs_la_SOURCES += fs/spmaps.c
libsilofs_la_SOURCES += fs/spxmap.c
libsilofs_la_SOURCES += fs/super.c
libsilofs_la_SOURCES += fs/super2.c
libsilofs_la_SOURCES += fs/symlink.c
libsilofs_la_SOURCES += fs/task.c
libsilofs_la_SOURCES += fs/ustage.c
libsilofs_la_SOURCES += fs/vstage.c
libsilofs_la_SOURCES += fs/xattr.c
libsilofs_la_SOURCES += mnt/mntconf.c
libsilofs_la_SOURCES += mnt/mntsvc.c
libsilofs_la_SOURCES += mnt/mstypes.h
libsilofs_la_SOURCES += fuse/fqtypes.c
libsilofs_la_SOURCES += fuse/fqtypes.h
libsilofs_la_SOURCES += fuse/fuse_abi.h
libsilofs_la_SOURCES += fuse/fuseq.c
libsilofs_la_SOURCES += run/appexec.c
libsilofs_la_SOURCES += run/delfs.c
libsilofs_la_SOURCES += run/env.c
libsilofs_la_SOURCES += run/envinst.c
libsilofs_la_SOURCES += run/ignite.c
libsilofs_la_SOURCES += run/mbr.c
libsilofs_la_SOURCES += run/opers.c
libsilofs_la_SOURCES += run/vfswrap.c
libsilofs_la_SOURCES += run/walk.c

noinst_HEADERS = $(NULL)
noinst_HEADERS += addr.h
noinst_HEADERS += base.h
noinst_HEADERS += base/atomic.h
noinst_HEADERS += base/atomic.h
noinst_HEADERS += base/avl.h
noinst_HEADERS += base/base64.h
noinst_HEADERS += base/bytebuf.h
noinst_HEADERS += base/iovec.h
noinst_HEADERS += base/hamming.h
noinst_HEADERS += base/hashfn.h
noinst_HEADERS += base/list.h
noinst_HEADERS += base/pipe.h
noinst_HEADERS += base/private.h
noinst_HEADERS += base/qalloc.h
noinst_HEADERS += base/socket.h
noinst_HEADERS += base/thread.h
noinst_HEADERS += base/times.h
noinst_HEADERS += base/uconv.h
noinst_HEADERS += base/utility.h
noinst_HEADERS += base/uuid.h
noinst_HEADERS += base/zcmpr.h
noinst_HEADERS += crypt.h
noinst_HEADERS += flags.h
noinst_HEADERS += fs.h
noinst_HEADERS += fuseq.h
noinst_HEADERS += nodes.h
noinst_HEADERS += pv.h
noinst_HEADERS += str.h
noinst_HEADERS += str/ascii.h
noinst_HEADERS += str/strbuf.h
noinst_HEADERS += str/strchr.h
noinst_HEADERS += str/strspan.h
noinst_HEADERS += str/strview.h
noinst_HEADERS += vfs.h
noinst_HEADERS += run.h
noinst_HEADERS += run/env.h
noinst_HEADERS += run/mbr.h
noinst_HEADERS += run/opers.h
noinst_HEADERS += run/walk.h
