-include $(top_builddir)/common.mk

AM_CFLAGS = $(WARN_CFLAGS)

libsilofsdir = $(libdir)
libsilofs_LTLIBRARIES = libsilofs.la
libsilofs_la_CPPFLAGS = $(NULL)
libsilofs_la_CPPFLAGS += -I$(top_builddir)/include
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/include
libsilofs_la_CPPFLAGS += -I$(top_srcdir)/lib
libsilofs_la_CPPFLAGS += -DSILOFS_USE_PRIVATE=1
libsilofs_la_CPPFLAGS += $(LIBGCRYPT_CFLAGS)
libsilofs_la_CPPFLAGS += $(PTHREAD_CFLAGS) $(PTHREAD_DEF)
libsilofs_la_LDFLAGS = $(NULL)
libsilofs_la_LDFLAGS += -version-info 0
libsilofs_la_LIBADD = $(NULL)
libsilofs_la_LIBADD += $(LIBS)
libsilofs_la_LIBADD += $(PTHREAD_LIBS)

libsilofs_la_SOURCES = $(NULL)
libsilofs_la_SOURCES += ondisk.c
libsilofs_la_SOURCES += version.c
libsilofs_la_SOURCES += flags.h

libsilofs_la_SOURCES += sys/syscall.c
libsilofs_la_SOURCES += sys/syscallx.c

libsilofs_la_SOURCES += infra/atomic.h
libsilofs_la_SOURCES += infra/avl.c
libsilofs_la_SOURCES += infra/avl.h
libsilofs_la_SOURCES += infra/base64.c
libsilofs_la_SOURCES += infra/base64.h
libsilofs_la_SOURCES += infra/bytebuf.c
libsilofs_la_SOURCES += infra/bytebuf.h
libsilofs_la_SOURCES += infra/iovec.c
libsilofs_la_SOURCES += infra/iovec.h
libsilofs_la_SOURCES += infra/hamming.c
libsilofs_la_SOURCES += infra/hamming.h
libsilofs_la_SOURCES += infra/hashfn.c
libsilofs_la_SOURCES += infra/hashfn.h
libsilofs_la_SOURCES += infra/list.c
libsilofs_la_SOURCES += infra/list.h
libsilofs_la_SOURCES += infra/logging.c
libsilofs_la_SOURCES += infra/memalloc.c
libsilofs_la_SOURCES += infra/panic.c
libsilofs_la_SOURCES += infra/pipe.c
libsilofs_la_SOURCES += infra/pipe.h
libsilofs_la_SOURCES += infra/private.h
libsilofs_la_SOURCES += infra/qalloc.c
libsilofs_la_SOURCES += infra/qalloc.h
libsilofs_la_SOURCES += infra/snprintf.c
libsilofs_la_SOURCES += infra/socket.c
libsilofs_la_SOURCES += infra/socket.h
libsilofs_la_SOURCES += infra/thread.c
libsilofs_la_SOURCES += infra/thread.h
libsilofs_la_SOURCES += infra/times.c
libsilofs_la_SOURCES += infra/times.h
libsilofs_la_SOURCES += infra/uconv.c
libsilofs_la_SOURCES += infra/uconv.h
libsilofs_la_SOURCES += infra/utility.h
libsilofs_la_SOURCES += infra/uuid.c
libsilofs_la_SOURCES += infra/uuid.h
libsilofs_la_SOURCES += infra/zcmpr.c
libsilofs_la_SOURCES += infra/zcmpr.h
libsilofs_la_SOURCES += infra.h

libsilofs_la_SOURCES += str/ascii.c
libsilofs_la_SOURCES += str/ascii.h
libsilofs_la_SOURCES += str/strbuf.c
libsilofs_la_SOURCES += str/strbuf.h
libsilofs_la_SOURCES += str/strchr.c
libsilofs_la_SOURCES += str/strchr.h
libsilofs_la_SOURCES += str/strspan.c
libsilofs_la_SOURCES += str/strspan.h
libsilofs_la_SOURCES += str/strview.c
libsilofs_la_SOURCES += str/strview.h
libsilofs_la_SOURCES += str.h

libsilofs_la_SOURCES += crypt/cipher.c
libsilofs_la_SOURCES += crypt/gcry.c
libsilofs_la_SOURCES += crypt/hmac.c
libsilofs_la_SOURCES += crypt/ivkey.c
libsilofs_la_SOURCES += crypt/kdf.c
libsilofs_la_SOURCES += crypt/mdigest.c
libsilofs_la_SOURCES += crypt/passwd.c
libsilofs_la_SOURCES += crypt/prand.c
libsilofs_la_SOURCES += crypt.h

libsilofs_la_SOURCES += addr/blobid.c
libsilofs_la_SOURCES += addr/blobid.h
libsilofs_la_SOURCES += addr/creds.c
libsilofs_la_SOURCES += addr/creds.h
libsilofs_la_SOURCES += addr/fsref.c
libsilofs_la_SOURCES += addr/fsref.h
libsilofs_la_SOURCES += addr/hash.c
libsilofs_la_SOURCES += addr/hash.h
libsilofs_la_SOURCES += addr/htox.c
libsilofs_la_SOURCES += addr/htox.h
libsilofs_la_SOURCES += addr/laddr.c
libsilofs_la_SOURCES += addr/laddr.h
libsilofs_la_SOURCES += addr/namestr.c
libsilofs_la_SOURCES += addr/namestr.h
libsilofs_la_SOURCES += addr/nmeta.c
libsilofs_la_SOURCES += addr/pnptr.c
libsilofs_la_SOURCES += addr/pnptr.h
libsilofs_la_SOURCES += addr/offlen.c
libsilofs_la_SOURCES += addr/offlen.h
libsilofs_la_SOURCES += addr/paddr.c
libsilofs_la_SOURCES += addr/paddr.h
libsilofs_la_SOURCES += addr/stype.c
libsilofs_la_SOURCES += addr/uniqid.c
libsilofs_la_SOURCES += addr/uniqid.h
libsilofs_la_SOURCES += addr.h

libsilofs_la_SOURCES += nodes/dirtyq.c
libsilofs_la_SOURCES += nodes/dirtyq.h
libsilofs_la_SOURCES += nodes/hmapq.c
libsilofs_la_SOURCES += nodes/hmapq.h
libsilofs_la_SOURCES += nodes/idsmap.c
libsilofs_la_SOURCES += nodes/idsmap.h
libsilofs_la_SOURCES += nodes/lcache.c
libsilofs_la_SOURCES += nodes/lcache.h
libsilofs_la_SOURCES += nodes/lnodes.c
libsilofs_la_SOURCES += nodes/lnodes.h
libsilofs_la_SOURCES += nodes/nodeview.c
libsilofs_la_SOURCES += nodes/nodeview.h
libsilofs_la_SOURCES += nodes/pcache.c
libsilofs_la_SOURCES += nodes/pcache.h
libsilofs_la_SOURCES += nodes/pnodes.c
libsilofs_la_SOURCES += nodes/pnodes.h
libsilofs_la_SOURCES += nodes/spools.c
libsilofs_la_SOURCES += nodes/spools.h
libsilofs_la_SOURCES += nodes.h

libsilofs_la_SOURCES += pstor/bldesc.c
libsilofs_la_SOURCES += pstor/bldesc.h
libsilofs_la_SOURCES += pstor/btnode.c
libsilofs_la_SOURCES += pstor/btnode.h
libsilofs_la_SOURCES += pstor/btree.c
libsilofs_la_SOURCES += pstor/btree.h
libsilofs_la_SOURCES += pstor/carve.c
libsilofs_la_SOURCES += pstor/carve.h
libsilofs_la_SOURCES += pstor/encdec.c
libsilofs_la_SOURCES += pstor/encdec.h
libsilofs_la_SOURCES += pstor/mapping.c
libsilofs_la_SOURCES += pstor/mapping.h
libsilofs_la_SOURCES += pstor/dstor.c
libsilofs_la_SOURCES += pstor/dstor.h
libsilofs_la_SOURCES += pstor/repo.c
libsilofs_la_SOURCES += pstor/repo.h
libsilofs_la_SOURCES += pstor/spnode.c
libsilofs_la_SOURCES += pstor/spnode.h
libsilofs_la_SOURCES += pstor/stage.c
libsilofs_la_SOURCES += pstor/stage.h
libsilofs_la_SOURCES += pstor/uber.c
libsilofs_la_SOURCES += pstor/uber.h
libsilofs_la_SOURCES += pstor.h

libsilofs_la_SOURCES += fs/dir.c
libsilofs_la_SOURCES += fs/dir.h
libsilofs_la_SOURCES += fs/file.c
libsilofs_la_SOURCES += fs/file.h
libsilofs_la_SOURCES += fs/filep.h
libsilofs_la_SOURCES += fs/flush.c
libsilofs_la_SOURCES += fs/format.c
libsilofs_la_SOURCES += fs/inode.c
libsilofs_la_SOURCES += fs/inode.h
libsilofs_la_SOURCES += fs/inops.c
libsilofs_la_SOURCES += fs/inops.h
libsilofs_la_SOURCES += fs/lspace.c
libsilofs_la_SOURCES += fs/lspace.h
libsilofs_la_SOURCES += fs/namei.c
libsilofs_la_SOURCES += fs/namei.h
libsilofs_la_SOURCES += fs/pglue.c
libsilofs_la_SOURCES += fs/pglue.h
libsilofs_la_SOURCES += fs/super.c
libsilofs_la_SOURCES += fs/super.h
libsilofs_la_SOURCES += fs/symlink.c
libsilofs_la_SOURCES += fs/symlink.h
libsilofs_la_SOURCES += fs/task.c
libsilofs_la_SOURCES += fs/task.h
libsilofs_la_SOURCES += fs/xattr.c
libsilofs_la_SOURCES += fs/xattr.h
libsilofs_la_SOURCES += fs.h
libsilofs_la_SOURCES += vfs.h

libsilofs_la_SOURCES += mnt/mntconf.c
libsilofs_la_SOURCES += mnt/mntsvc.c
libsilofs_la_SOURCES += mnt/mstypes.h

libsilofs_la_SOURCES += fuse/fqtypes.c
libsilofs_la_SOURCES += fuse/fqtypes.h
libsilofs_la_SOURCES += fuse/fuse_abi.h
libsilofs_la_SOURCES += fuse/fuseq.c
libsilofs_la_SOURCES += fuseq.h

libsilofs_la_SOURCES += run/appexec.c
libsilofs_la_SOURCES += run/delfs.c
libsilofs_la_SOURCES += run/env.c
libsilofs_la_SOURCES += run/env.h
libsilofs_la_SOURCES += run/envinst.c
libsilofs_la_SOURCES += run/ignite.c
libsilofs_la_SOURCES += run/mbr.c
libsilofs_la_SOURCES += run/mbr.h
libsilofs_la_SOURCES += run/opers.c
libsilofs_la_SOURCES += run/opers.h
libsilofs_la_SOURCES += run/vfswrap.c
libsilofs_la_SOURCES += run/walk.c
libsilofs_la_SOURCES += run/walk.h
libsilofs_la_SOURCES += run.h
