---
name: "SiloFS: build deploy and test"

on:
  push:
    branches: ['*']
  pull_request:
    branches: [$default-branch]

jobs:
  validate:
    name: Validate build environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: System
        run: uname -a
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Require build tools
        run: ./misc/requiredeps.sh
      - name: Require install tool
        run: apt --version

  codelint:
    name: Lint code style
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Check C-style
        run: ./cstylelint.sh
      - name: Verify code formatting
        run: ./astyleall.sh

  developer-build:
    name: Build with developer flags
    runs-on: ubuntu-latest
    needs: codelint
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Build without optimization
        run: make -f devel.mk O=0
      - name: Reset
        run: make -f devel.mk reset
      - name: Re-build
        run: make -f devel.mk O=2

  build:
    name: Build only
    runs-on: ubuntu-latest
    needs: codelint
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: ./configure --enable-unitests=no
      - name: Build
        run: make

  check:
    name: Run unit-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: ./configure --enable-unitests=yes
      - name: Build
        run: make
      - name: Check
        run: make check
      - name: Dist check
        run: make distcheck

  static-analyze:
    name: Run static-code analysis
    runs-on: ubuntu-latest
    needs: developer-build
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Run clang static-analyzer
        run: ./misc/clangscanbuild.sh

  packagize:
    name: Create deb package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Packagize
        run: ./dist/packagize-deb.sh

  install:
    name: Install deb package
    runs-on: ubuntu-latest
    needs: packagize
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install deps
        run: sudo ./misc/installdeps.sh
      - name: Packagize
        run: ./dist/packagize-deb.sh
      - name: Install
        run: sudo apt install ./build/dist/silofs_*.deb
      - name: Verify installation
        run: silofs --version

  # vfstests:
  #   name: Run sanity smoke-tests suite
  #   runs-on: ubuntu-latest
  #   needs:
  #     - check
  #     - static-analyze
  #     - install
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Update
  #       run: sudo apt-get update
  #     - name: Install deps
  #       run: sudo ./misc/installdeps.sh
  #     - name: Packagize
  #       run: ./dist/packagize-deb.sh
  #     - name: Install
  #       run: sudo apt install ./build/silofs_*.deb
  #     - name: Verify installation
  #       run: silofs --version
  #     - name: Prepare tests
  #       run: |
  #         sudo mkdir -p /mnt/test
  #         sudo chmod 777 /mnt/test
  #         sudo sh -c "echo /mnt/test >> /etc/silofs/mountd.conf"
  #         sudo systemctl restart silofs-mountd.service
  #     - name: Make file-system
  #       run: |
  #         mkdir ./silofs-tests
  #         silofs mkfs -s 32G ./silofs-tests
  #     - name: Mount file-system
  #       run: silofs mount ./silofs-tests /mnt/test
  #     - name: Run simple I/O
  #       run: |
  #         mkdir -p /mnt/test/A
  #         dd if=/dev/zero of=/mnt/test/A/z bs=1M count=1024
  #         rm /mnt/test/A/z
  #     - name: Run sanity smoke-tests
  #       run: silofs-vfstests /mnt/test/A
  #     - name: Un-mount file-system
  #       run: silofs umount /mnt/test
  #     - name: Cleanup repo
  #       run: rm -rf ./silofs-tests

  completion:
    name: End workflow
    runs-on: ubuntu-latest
    needs:
      - check
      - install
      # - vfstests
    steps:
      - name: Done
        run: date
